### ISSUE TITLE
Project's setup to-do

### ISSUE THREAD

**Issue by mirzahilmi** [Lab-ICN/water-potability-backend#1]
# TODOs
- [ ] Project's README
- [ ] Base environment configured with nix flake
- [ ] Base project structure (clean architecture)
- [ ] Go's linter configured as CI workflow

**Comment by mirzahilmi** [comment]
Buat sekarang, ada beberapa opsi style struktur projectnya yang ngikutin clean archnya uncle Bob:
- https://github.com/bxcodec/go-clean-arch
- https://github.com/DoWithLogic/golang-clean-architecture
- https://github.com/evrone/go-clean-template
- https://github.com/amitshekhariitbhu/go-backend-clean-architecture

kalo ada saran/pendapat, bisa reply komentar ini ya :shipit:
